---
version: "3"

services:
  devopsdb:
    image: mdprasad/automation:db
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  application:
    image: mdprasad/automation:app
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetwork
    deploy:
      replicas: 3

networks:
  mynetwork:
    driver: overlay
